---
project: lib_src
title: SAMPLE RATE CONVERSION
version: 2.7.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  root_doc: doc/programming_guide/index.rst
  doxygen_projects:
    lib_xcore_math:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/programming_guide/index:
      pdf_title: "{{title}} - Programming Guide"
      pdf_filename: "{{project}}_programming_guide_v{{version}}"
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{project}}_v{{version}}_readme'
      pdf_short: yes
